# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 14:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170220_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='failure',
            name='exception_type',
        ),
        migrations.RemoveField(
            model_name='failure',
            name='value',
        ),
    ]
