# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170220_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.Subreddit')),
            ],
        ),
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='edge',
            name='graph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Graph'),
        ),
        migrations.AddField(
            model_name='edge',
            name='mods',
            field=models.ManyToManyField(to='api.User'),
        ),
        migrations.AddField(
            model_name='edge',
            name='to_sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.Subreddit'),
        ),
        migrations.AddField(
            model_name='subreddit',
            name='graph',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Graph'),
        ),
    ]
