# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20170223_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdgeModRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_mod_source', models.BooleanField(default=True)),
                ('current_mod_target', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='edge',
            name='current_mod_source',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='current_mod_target',
        ),
        migrations.AlterField(
            model_name='edge',
            name='mods',
            field=models.ManyToManyField(related_name='old_mods', to='api.User'),
        ),
        migrations.AddField(
            model_name='edgemodrelation',
            name='edge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Edge'),
        ),
        migrations.AddField(
            model_name='edgemodrelation',
            name='mod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
        migrations.AddField(
            model_name='edge',
            name='new_mods',
            field=models.ManyToManyField(through='api.EdgeModRelation', to='api.User'),
        ),
    ]
