# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20170223_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edge',
            old_name='from_sub',
            new_name='source',
        ),
        migrations.AddField(
            model_name='edge',
            name='current_mod_source',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='edge',
            name='current_mod_target',
            field=models.BooleanField(default=True),
        ),
    ]
