# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 16:08
from __future__ import unicode_literals

from django.db import migrations

def fix_edges(apps, schema_editor):
    Edge = apps.get_model('api', 'Edge')
    EdgeModRelation = apps.get_model('api', 'EdgeModRelation')

    edge_rels = []
    for edge in Edge.objects.all():
        for mod in edge.mods.all():
            edge_rels.append(EdgeModRelation(edge=edge, mod=mod))
    EdgeModRelation.objects.bulk_create(edge_rels)

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20170224_1607'),
    ]

    operations = [
        migrations.RunPython(fix_edges)
    ]
