# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 15:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20170223_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edge',
            old_name='to_sub',
            new_name='target',
        ),
    ]
