# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 16:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_edge_mods'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edge',
            old_name='new_mods',
            new_name='mods',
        ),
    ]
