# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 16:15
from __future__ import unicode_literals

from django.db import migrations


def removal_events_update(apps, schema_editor):
    SubredditEventDetail = apps.get_model('api', 'SubredditEventDetail')
    EdgeModRelation = apps.get_model('api', 'EdgeModRelation')
    Edge = apps.get_model('api', 'Edge')


    for detail in SubredditEventDetail.objects.filter(addition=False):
        print("Remove " + detail.user.username + ' from ' + detail.event.sub.name_lower)
        for edge in Edge.objects.filter(source=detail.event.sub):
            for rel in EdgeModRelation.objects.filter(edge=edge, mod=detail.user):
                print('Found with source: ' + rel.edge.source.name_lower + ' target: ' + rel.edge.target.name_lower)
                rel.current_mod_source = False
                rel.save()

        for edge in Edge.objects.filter(target=detail.event.sub):
            for rel in EdgeModRelation.objects.filter(edge=edge, mod=detail.user):
                print('Found with source: ' + rel.edge.source.name_lower + ' target: ' + rel.edge.target.name_lower)
                rel.current_mod_target = False
                rel.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20170224_1614'),
    ]

    operations = [
        migrations.RunPython(removal_events_update)
    ]
