# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 07:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LastChecked',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('last_checked', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0))),
            ],
        ),
        migrations.CreateModel(
            name='Subreddit',
            fields=[
                ('name_lower', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=22, unique=True)),
                ('subscribers', models.IntegerField()),
                ('last_checked', models.DateTimeField(auto_now_add=True)),
                ('last_changed', models.DateTimeField(auto_now_add=True)),
                ('forbidden', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SubredditQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='subredditquery',
            name='mods',
            field=models.ManyToManyField(to='data.User'),
        ),
        migrations.AddField(
            model_name='subredditquery',
            name='sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Subreddit'),
        ),
    ]
