# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_subreddit_last_changed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subreddit',
            name='name',
            field=models.CharField(max_length=22, primary_key=True, serialize=False),
        ),
    ]
