# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 22:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20170214_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='subredditquery',
            name='prev',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.SubredditQuery'),
        ),
    ]
