# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 22:22
from __future__ import unicode_literals

from django.db import migrations

def update_prev(apps, schema_editor):
    SubredditQuery = apps.get_model('data', 'SubredditQuery')
    for query in SubredditQuery.objects.all():
        if query.prev is None:
            query.prev = query
            query.save()

class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_subredditquery_prev'),
    ]

    operations = [
        migrations.RunPython(update_prev)
    ]
