# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 05:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20170121_1316'),
        ('data', '0004_lastchecked'),
    ]

    operations = [
    ]
