# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 08:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_merge_20170122_0556'),
        ('data', '0005_auto_20170122_0824'),
    ]

    operations = [
    ]
