# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20170122_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='subreddit',
            name='name_lower',
            field=models.CharField(default='', max_length=22),
            preserve_default=False,
        ),
    ]
