# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 13:01
from __future__ import unicode_literals

from django.db import migrations

def fix_name_cols(apps, schema_editor):
    Subreddit = apps.get_model("data", "Subreddit")
    SubredditQuery = apps.get_model("data", "SubredditQuery")

    for sub in Subreddit.objects.all():
        name = sub.name
        lname = sub.name.lower()
        if Subreddit.objects.filter(name_lower=lname).count() == 0:
            print('Adding lower name to  ' + name)
            sub.name_lower = lname
            sub.save()
        else:
            print('Found duplicate with ' + name)
            dup = Subreddit.objects.get(name_lower=lname)
            for query in sub.subredditquery_set.all():
                query.subreddit = dup
                query.save()


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_subreddit_name_lower'),
    ]

    operations = [
        migrations.RunPython(fix_name_cols),
    ]
