# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 13:17
from __future__ import unicode_literals

from django.db import migrations

def delete_dead_rows(apps, schema_editor):
    Subreddit = apps.get_model("data", "Subreddit")

    for sub in Subreddit.objects.filter(name_lower=''):
        sub.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20170123_1301'),
    ]

    operations = [
        migrations.RunPython(delete_dead_rows),
    ]
