# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20170215_0908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subredditeventdetail',
            name='event_type',
        ),
        migrations.AddField(
            model_name='subredditevent',
            name='new',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subredditeventdetail',
            name='addition',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subredditevent',
            name='previous_check',
            field=models.DateTimeField(null=True),
        ),
    ]
