# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_merge_20170123_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subreddit',
            name='name_lower',
            field=models.CharField(max_length=22, unique=True),
        ),
    ]
