# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20170123_1321'),
        ('data', '0006_merge_20170122_0825'),
    ]

    operations = [
    ]
