# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 11:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20170215_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subredditquery',
            name='mods',
        ),
        migrations.RemoveField(
            model_name='subredditquery',
            name='prev',
        ),
        migrations.RemoveField(
            model_name='subredditquery',
            name='sub',
        ),
        migrations.DeleteModel(
            name='SubredditQuery',
        ),
    ]
