# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20170123_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='subreddit',
            name='forbidden',
            field=models.BooleanField(default=False),
        ),
    ]
