# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20170215_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subreddit',
            name='last_changed',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='subreddit',
            name='subscribers',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
