# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_auto_20170215_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subreddit',
            name='forbidden',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
